### ISSUE TITLE
How can I solve this runtime error?

### ISSUE THREAD

**Issue by Hey-Sweety** [FutureXiang/Diffusion#4]
⭐Running command:
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 cifar_guide.py --config config/cifar_conditional.yaml --use_amp
-----------------------------------------
⭐Error message:
usage: cifar_guide.py [-h] [--config CONFIG] [--local_rank LOCAL_RANK] [--use_amp]
cifar_guide.py: error: unrecognized arguments: --local-rank=0
usage: cifar_guide.py [-h] [--config CONFIG] [--local_rank LOCAL_RANK] [--use_amp]
cifar_guide.py: error: unrecognized arguments: --local-rank=1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 46040) of binary.
-----------------------------------------
Thanks in advance❤

**Comment by FutureXiang** [comment]
Hi,

This error is related to the distributed launch mode of PyTorch. Please refer to [this official document](https://pytorch.org/docs/stable/elastic/run.html).

This repo is built on older (<2.0) PyTorch versions. If you are using `PyTorch>=2.0.0`, you may want to use `torchrun` instead of `python -m torch.distributed.launch` and use the following code in the main function:
```py
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str)
    parser.add_argument("--use_amp", action='store_true', default=False)
    opt = parser.parse_args()
    opt.local_rank = int(os.environ['LOCAL_RANK'])
    print0(opt)

    init_seeds(no=opt.local_rank)
    dist.init_process_group(backend='nccl')
    torch.cuda.set_device(opt.local_rank)
    train(opt)
```

**Comment by Hey-Sweety** [comment]
Thanks for your reply, future✈
I have modified the code with your help, and successfully ran it on 2 A6000 GPUs, but it fails to train on 4 GTX 4090 GPUs. And there was no error message reported, just unable to enter training and print losses.
The CUDA versions of two kinds of GPUs are the same, and they are on the same machine. Is it because the memory capacity of the 4090 GPUs is too small?

**Comment by Hey-Sweety** [comment]
Supplement:
a single GTX 4090: Successfully run.
4 GTX 4090: Failed ❌.
a single A6000: Successfully run.
2 A6000: Successfully run.

**Comment by FutureXiang** [comment]
Hi,

I don't think it's caused by the smaller CUDA memory, since I'm running these models successfully on 3080ti gpus.
Don't forget to modify `nproc_per_node=2` to `nproc_per_node=4` when using 4 GTX 4090 gpus.

**Comment by Hey-Sweety** [comment]
Get it, I'll try again. 
Thank you once again.
